language: java
jdk:
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
  - oraclejdk11
  - openjdk12
  - openjdk13
  - openjdk14
  - openjdk15
sudo: false
script: mvn clean package -Dgpg.skip=true
after_success:
  - mvn clean test cobertura:cobertura coveralls:report
  - mvn test jacoco:report
  - if [ "$JAVA_HOME" = "/home/travis/oraclejdk11" ]; then mvn test cobertura:cobertura coveralls:report; fi
  - bash <(curl -s https://codecov.io/bash)
