language: java
jdk:
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
sudo: false
script: mvn clean package -Dgpg.skip=true
after_success:
  - mvn clean test cobertura:cobertura coveralls:report
  - bash <(curl -s https://codecov.io/bash)
