language: java
jdk:
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
  - oraclejdk11
  - openjdk12
  - openjdk13
  - openjdk14
  - openjdk15
sudo: false
script: mvn clean package -Dgpg.skip=true -U
after_success:
  - if [ "$JAVA_HOME" = "/usr/lib/jvm/java-1.8.0-openjdk-amd64" ]; then mvn test cobertura:cobertura coveralls:report; fi
  - mvn test jacoco:report
  - bash <(curl -s https://codecov.io/bash)
